name: GitLab Sync

on:
  push:
    branches:
      - main
      - develop
  delete:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 🔥 magia: clone completo, niente errori nel mirror

      - name: Sync to GitLab
        uses: anmolnagpal/gitlab-mirror-and-ci-action@v2.0.7
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          gitlab_username: ${{ secrets.GITLAB_USERNAME }}
          gitlab_password: ${{ secrets.GITLAB_PASSWORD }}
          force: true
